### ISSUE TITLE
Confirmación sobre nombres de columnas en los archivos .csv [documentacion]

### ISSUE THREAD

**Issue by ebravofm** [labmsystem/lab_prueba_fruitycert#3]
Solo para confirmar: ¿No tenemos acceso a los nombres de las columnas en los archivos .csv proporcionados?
Al revisar las tablas (TablonInspecciones.csv, ParametrosInspeccion.csv, AtributosCliente.csv, AtributosLotes.csv), parece que los archivos no contienen encabezados, y debemos asumir qué atributo corresponde a cada columna basándonos en los valores encontrados en cada una.

¿Es correcto este entendimiento, o hay algún recurso/documentación adicional que nos permita identificar con certeza a qué atributo corresponde cada columna?

Gracias de antemano por la aclaración.

**Comment by nbalbontin** [comment]
Hola Emilio,
Efectivamente las tablas no tienen el nombre de las columnas y **eso es un error**. Hemos actualizado los datos para que ahora contengan los nombres de las columnas.
Disculpa la demora en la respuesta! De todas formas, por esto, **daremos 3 días hábiles más**.
Saludos!
